name: anomaly-detection-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip=23.3.1
  - pip:
      - azureml-defaults
      - inference-schema
      - scikit-learn==1.3.2
      - numpy==1.24.3
      - onnxruntime==1.16.3
